export const REMAINING_TEXT_BODY="REMAINING_TEXT_BODY";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST"
export const LOGIN = "LOGIN";
export const SET_PROFILE_PHOTO = "SET_PROFILE_PHOTO";